# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: React with Node.js CI Pipeline

# Trigger the workflow on push or pull request, not just on releases
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Set up Node.js (version 20 in this case)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies using npm ci
      - run: npm ci

      # Run your test suite
      - run: npm test

      # Build the React application
      - run: npm run build

  # If you also want to publish to GitHub Packages or another registry, keep the following job
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout the code again for the publish job
      - uses: actions/checkout@v4

      # Set up Node.js with registry-url for GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      # Install dependencies and publish the package
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
