# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: CI/CD  Pipeline

# Trigger the workflow on push or pull request, not just on releases
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



  
